services:
    netgen_open_graph.handler.abstract:
        class: Netgen\Bundle\OpenGraphBundle\Handler\Handler

    netgen_open_graph.handler.field_type.abstract:
        class: Netgen\Bundle\OpenGraphBundle\Handler\FieldType\Handler
        parent: netgen_open_graph.handler.abstract
        arguments:
            - "@ezpublish.field_helper"
            - "@ezpublish.translation_helper"

    netgen_open_graph.handler.literal.text:
        class: Netgen\Bundle\OpenGraphBundle\Handler\Literal\Text
        parent: netgen_open_graph.handler.abstract
        lazy: true
        tags:
            - { name: netgen_open_graph.meta_tag_handler, alias: literal/text }

    netgen_open_graph.handler.field_type.text_line:
        class: Netgen\Bundle\OpenGraphBundle\Handler\FieldType\TextLine
        parent: netgen_open_graph.handler.field_type.abstract
        lazy: true
        tags:
            - { name: netgen_open_graph.meta_tag_handler, alias: field_type/ezstring }

    netgen_open_graph.handler.field_type.text_block:
        class: Netgen\Bundle\OpenGraphBundle\Handler\FieldType\TextBlock
        parent: netgen_open_graph.handler.field_type.abstract
        lazy: true
        tags:
            - { name: netgen_open_graph.meta_tag_handler, alias: field_type/eztext }

    netgen_open_graph.handler.field_type.xml_text:
        class: Netgen\Bundle\OpenGraphBundle\Handler\FieldType\XmlText
        parent: netgen_open_graph.handler.field_type.abstract
        lazy: true
        tags:
            - { name: netgen_open_graph.meta_tag_handler, alias: field_type/ezxmltext }

    netgen_open_graph.handler.field_type.image:
        class: Netgen\Bundle\OpenGraphBundle\Handler\FieldType\Image
        parent: netgen_open_graph.handler.field_type.abstract
        lazy: true
        arguments:
            - "@ezpublish.fieldType.ezimage.variation_service"
            - "@request_stack"
            - "@?logger"
        tags:
            - { name: netgen_open_graph.meta_tag_handler, alias: field_type/ezimage }
